---
- hosts: test
  user: root
  tasks:
   -  name: creating required directory
      file:
         path: /mnt/artifacts
         state: directory
         mode: "u=rwx,g=rwx,o=rwx"
   -  name: copying artifacts to desired location
      copy:
         src: target/spring-petclinic-2.4.5.jar
         dest: /mnt/artifacts/
